---
version: '3'
 
services:
  packet_buddy:
    image: johncapobianco/packet_buddy:packet_buddy
    container_name: packet_buddy
    restart: always
    environment:
      - OPENAI_API_KEY=sk-pj-abcd1234       
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile   
    ports:
      - "8505:8505"     
    volumes:
      - ./config.toml:/root/.streamlit/config.toml
